allowBuilds:
  esbuild: false

minimumReleaseAgeExclude:
  - '@unocss/*'
  - unocss@66.7.2 || 66.9.2 || 66.10.0
  - '@types/node@26.4.1'
  - '@devframes/service-shiki@0.9.11'
  - '@devframes/vite@0.9.11'
  - devframe@0.9.11
  - vitepress@2.0.0-alpha.20
